### ISSUE TITLE
How to expose to NodePort service

### ISSUE THREAD

**Issue by superdit** [ghouscht/metrics-server-exporter#3]
I'm trying to expose to NodePort, so I can scrape outside k8s cluster, I try this service but NodePort url not working

apiVersion: v1
kind: Service
metadata:
  name: metrics-server-exporter
  labels:
    app: metrics-server-exporter
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 31003
  selector:
    app: metrics-server-exporter

**Comment by ghouscht** [comment]
Hi,
I will archive this repository, sorry for not getting back on you in time. I hope you were able to resolve your problems.
Regards, Thomas
